apiVersion: v1
kind: Namespace
metadata:
  name: __project__-__name__ # {"$kpt-set":"destination-namespace"}
  annotations:
    argocd.argoproj.io/sync-wave: "-2" # Ensure the namespace is created before the argo project
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: __name__ # {"$kpt-set":"name"}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: __project__-__name__ # {"$kpt-set":"destination-namespace"}
    server: https://kubernetes.default.svc
  project: __project__ # {"$kpt-set":"project"}
  source:
    path: . # {"$kpt-set":"repo-path"}
    repoURL: __repo__ # {"$kpt-set":"repo"}
    targetRevision: HEAD # {"$kpt-set":"target-revision"}
