apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.name}}
    service: {{.Values.name}}
spec:
  ports:
    - name: http
      port: {{.Values.port}}
      targetPort: {{.Values.containerPort}}
  selector:
    app: {{.Values.name}}
