apiVersion: apps/v1
kind: Deployment
metadata:
  name: __name__ # {"$kpt-set":"name"}
  namespace: __namespace__ # {"$kpt-set":"namespace"}
spec:
  replicas: 1 # {"$kpt-set":"replicas"}
  selector:
    matchLabels:
      app: __name__ # {"$kpt-set":"name"}
      version: v1
  template:
    metadata:
      labels:
        app: __name__ # {"$kpt-set":"name"}
        version: v1
    spec:
      serviceAccountName: __name__ # {"$kpt-set":"name"}
      containers:
      - image: docker.io/kennethreitz/httpbin # {"$kpt-set":"image"}
        imagePullPolicy: IfNotPresent
        name: __name__ # {"$kpt-set":"name"}
        ports:
        - containerPort: 80 # {"$kpt-set":"container-port"}
