apiVersion: v1
kind: Service
metadata:
  name: __name__ # {"$kpt-set":"name"}
  namespace: __namespace__ # {"$kpt-set":"namespace"}
  labels:
    app: __name__ # {"$kpt-set":"name"}
    service: __name__ # {"$kpt-set":"name"}
spec:
  ports:
  - name: http
    port: 8000 # {"$kpt-set":"port"}
    targetPort: __container-port__ # {"$kpt-set":"container-port"}
  selector:
    app: __name__ # {"$kpt-set":"name"}
